### ISSUE TITLE
Question: How do you retain the color format?

### ISSUE THREAD

**Issue by djmtype** [apart-edgar/figma-tokens-with-style-dictionary#1]
It seems after running the Token Transformer tool, all colors that were specified as rgba get returned as their hex equivalent. 

Adding `'attribute/color', 'color/rgb'` to SD's transforms in its config file will not convert them back to rgba either. 

Original json token: 
```
"disabled": {
          "value": "rgba({color.white}, 0.7)",
          "type": "color",
          "description": "Color On Primary Disabled"
        }
```

After Token Transformer process: 
```
"disabled": {
        "value": "#ffffffb3",
        "type": "color",
        "description": "Color On Primary Disabled"
      }
```

**Comment by apart-edgar** [comment]
Hey @djmtype,

Thank you for your feedback, that's a good catch!

I've uploaded a fixed version. By adding the [color/css transform](https://amzn.github.io/style-dictionary/#/transforms?id=colorcss) to the Style Dictionary config, it seems to fix the problem.

Style Dictionary is now able to interpret the values compiled by [token-transformer](https://www.npmjs.com/package/token-transformer).

This [blogpost](https://www.michaelmang.dev/blog/generating-design-token-theme-shades-with-style-dictionary) helped me figure it out.

Let me know if that fixes the problem for you too.

Cheers,

**Comment by djmtype** [comment]
Thanks @apart-edgar, that seems to have done the trick!

BTW, your ReadMe for this repo should be referenced on the official Figma Token's docs as it's been very helpful!

**Comment by apart-edgar** [comment]
@djmtype Perfect!

Thank you very much for your feedback. That's great to know! I'll see if I can submit it to the Figma Tokens Plugin creator but not sure I saw a section with external resources in the documentation.
